### ISSUE TITLE
Mage

### ISSUE THREAD

**Issue by Crpeekaboo** [Vae2009/ConROC#11]
During playing the Mage the only thing that shows that works is the Armor buff and Arcane Intellect buff..
All other spells do not showing to be cast.
Selecting any or all of the Runes, Fillers, Cool downs and AoE's under Mage Spells doesn't help...
It's like it's turned off.

There are no error messages for me to show.
I did uninstall and reinstalled with no luck.

Thanks

**Comment by Crpeekaboo** [comment]
Reporting back on Mage after uodate.
Still same issue not showing any spells to cast.

Thanks

**Comment by Crpeekaboo** [comment]
Played Mage a lot yesterday.
Un-installed all addons, reinstalled ConRo for Mage and ran a wow scan repair and still doesn't show any spells to cast. It's like something is turned off not allowing or reconize any spells. Today have this as well attached. I also tried selecting several different spells in Mage spell list.
![20241229_081803](https://github.com/user-attachments/assets/d1e0c147-1d47-4a6d-89b9-7121878c4b26)

**Comment by Starlynk1** [comment]
The screenshot issue should be resolved with issue #13 when it is implemented

**Comment by Vae2009** [comment]
I am doing a major update this weekend. It requires that I upload all
classes at the same time. So it is taking me some extra time to be able to
issue a fix. 6 more classes to go.

**Comment by Crpeekaboo** [comment]
Good morning,
Like your newer layout.
I played the Mage some to see if spells would work. It still the same and does show what spell to cast. The only thing I see that will show is Arcane Intellect when needing refreshed, Ice Armor and Frost Nova...seems only buffs for most part showing. 
![20241231_085829](https://github.com/user-attachments/assets/59f7b42a-c28c-4daa-9bf3-eefab0bedb6f)

**Comment by Vae2009** [comment]
Trying to find the issue.

**Comment by Vae2009** [comment]
I think I may have found it. Uploaded now, in next update.
